### ISSUE TITLE
vrecord installation issue

### ISSUE THREAD

**Issue by jimhone** [amiaopensource/vrecord#722]
While trying to install record using Homebrew, I consistently get the following message:

Installing dependencies for amiaopensource/amiaos/vrecord: amiaopensource/amiaos/ffmpegdecklink, bash and luajit-openresty
==> Installing amiaopensource/amiaos/vrecord dependency: amiaopensource/ami
Error: An exception occurred within a child process:
  NameError: undefined local variable or method `os' for #<Formulary::FormulaNamespace25da0e2bce32b8800d0a7d1e08257e67::Ffmpegdecklink:0x00007fee9d89b708>

Running MAC OS 12.12.1
Latest driver for Blackmagic Desktop Video Setup (12.2.2)
ffmpeg version 4.4-with-options

Installing with "--ignore dependencies"  results in sluggish startup, setup and near instantaneous exit when I hit record.

Any insights or possible fixes would be appreciated.

**Comment by dericed** [comment]
Thanks @jimhone. @privatezero and I were trying to resolve this as it's a regression since https://github.com/amiaopensource/homebrew-amiaos/pull/310/files.

**Comment by retokromer** [comment]
On my end, https://github.com/amiaopensource/homebrew-amiaos/pull/315 fixes it.

**Comment by privatezero** [comment]
Hi @retokromer it seems that we might be dealing with a couple of separate issues here - on my end both the current formula as well as https://github.com/amiaopensource/homebrew-amiaos/pull/315 fail to build with the error:

> NameError: undefined local variable or method `os' for #<Formulary::FormulaNamespacefe12a7c6a50e5a93aa38c2605bc209bd::Ffmpegdecklink:0x0000000004058f30>

This is fixed by changing the method of OS check along the lines of what is in https://github.com/amiaopensource/homebrew-amiaos/tree/fix-system-check

This lets everything build correctly on my end (Ubuntu 20.04) but seems to still have a separate problem on the macOS side - is this what the file name change in https://github.com/amiaopensource/homebrew-amiaos/pull/315 fixes? I am unfortunately unable to test on macOS right now.

**Comment by privatezero** [comment]
@retokromer I think I just actually identified the OS check issue - there was a spot where there was a check written as `if os.mac?` instead of `if OS.mac` - but since that has been removed in the version rollback @dericed just did I suppose that is all worked out as well

**Comment by privatezero** [comment]
@jimhone we've rolled back the version of the dependency causing issue for now - if you run `brew update` and try reinstalling, things should be working now!

**Comment by retokromer** [comment]
@privatezero Indeed! That’s to enable neon.

**Comment by jimhone** [comment]
Reinstall went smoothly.  I'm about 40 minutes into an 85 minute capture and things are looking good. If there are any further issues, I'll let you know.

Many thanks for your help.

**Comment by jimhone** [comment]
Success!
